In [ ]:
import pandas as pd

excel_path = ("../data/raw/classification/Book1.xlsx")

#inspect the namnes without reading all data into memory
excel_file = pd.ExcelFile(excel_path)
print("Found Sheets:", excel_file.sheet_names)

Found Sheets: ['COMMUNICATION', 'CLEARANCE', 'AOsMEMOs', 'LEAVES']

In [40]:
header_rows = {
    "COMMUNICATION":2,
    "CLEARANCE": 1,
    "AOsMEMOs": 3,
    "LEAVES": 0,
}

for sheets in excel_file.sheet_names:
    header_row = header_rows.get(sheets,0)
    
    df = pd.read_excel(
        excel_file,
        sheet_name=sheets,
        header=header_row,

    )
    
    print(f"\n--- [{sheets}] ---")
    display(df)

--- [COMMUNICATION] ---

,DATE,CONTROL#,SUBJECT,DESCRIPTION,TYPE,OFFICE/PERSON FROM,OFFICE/UNIT CONCERNED,REMARKS,REMARKS 2,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,2024-01-02 00:00:00,2024-01-02-COM-OUT-01,REQUEST TO RENDER OVERTIME,REQUEST TO RENDER OVERTIME,OUT,ACCOUNTING,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-02 00:00:00,2024-01-02-COM-IN-01,PFC MEETING,"ADJUSTED RECEIPTS PROGRAM, SETTING OF POLICY, ...",IN,PROVINCIAL FINANCE COMMITTEE,"PROVINCIAL TREAS., ASST. PPDO AND PROVINCIAL A...",NaN,NaN,NaN,NaN,NaN
2,2024-01-02 00:00:00,2024-01-02-COM-IN-02,NOTICE OF ASSIGNMENT/ GRANT OF SECURITY INTEREST,CREDIT LINE AGREEMENT DATE 29 DECEMBER 2023,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-03 00:00:00,2024-01-03-COM-IN-01,FY 2023 SUPPLEMENTAL BUDGET NO.02,FY 2023 SUPPLEMENTAL BUDGET NO.02,IN,DEPARTMENT OF BUDGET AND MANAGEMENT,HONORABLE MEMBERS OF THE SANGGUNIANG PANLALAWIGAN,NaN,NaN,NaN,NaN,NaN
4,2024-01-04 00:00:00,2024-01-04-COM-OUT-01,REQUEST FOR AN OPINION REGARDING THE INCLUSION...,REQUEST FOR AN OPINION REGARDING THE INCLUSION...,OUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2280,2026-09-22 00:00:00,2026-09-22-COM-OUT-02,REPLY TO LETTER RE: VOUCHERS OF C.J.T PASCUAL ...,REPLY TO LETTER RE: VOUCHERS OF C.J.T PASCUAL ...,OUT,ACCOUNTING,TREASURY,NaN,NaN,NaN,NaN,NaN
2281,2026-09-22 00:00:00,2026-09-22-COM-IN-05,COA DECISION NO. 2026-004,COA DECISION NO. 2026-004: REQUEST OF DR. CAYE...,IN,PRRU,ACCOUNTING,NaN,NaN,NaN,NaN,NaN
2282,2026-09-22 00:00:00,2026-09-22-COM-OUT-03,INDIVIDUAL PERFORMANCE COMMITMENT AND REVIEW (...,INDIVIDUAL PERFORMANCE COMMITMENT AND REVIEW (...,OUT,ACCOUNTING,HRMO,NaN,NaN,NaN,NaN,NaN
2283,2026-09-22 00:00:00,2026-09-22-COM-IN-06,NOTICE OF MEETING: CONSULTATIVE MEETING ON SEP...,NOTICE OF MEETING: CONSULTATIVE MEETING ON SEP...,IN,PEO,ACCOUNTING,MEETING,NaN,NaN,NaN,NaN
2284,2026-09-23 00:00:00,2026-09-23-COM-IN-01,SUBMISSION OF PROPOSED PROJECT FOR NTLB AGRICU...,SUBMISSION OF PROPOSED PROJECT FOR NTLB AGRICU...,IN,MUNICIPALITY OF STO. NIÑO,ACCOUNTING,NaN,NaN,NaN,NaN,NaN

--- [CLEARANCE] ---

,2024-11-20 00:00:00,2024-11-20-CLR-01,"ALAN, MARILYN T.",PEO,RETIREMENT,RELEASED,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2024-11-22,2024-11-22-CLR-01,"MATAMMU, MARIA PEACHINA B.",PHO,TRAVEL ABROAD,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-22,2024-11-22-CLR-02,"CARAG, ROGELIO",NaN,RETIREMENT,RELEASED,2024-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-11-25,2024-11-25-CLR-01,"BICCAN, CARIDAD",VET,RETIREMENT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-11-25,2024-11-25-CLR-02,"CALABUNG, AMELIA",VET,RETIREMENT,RELEASED,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-11-26,2024-11-26-CLR-01,"MELAD, VIRGILIO M",NaN,RETIREMENT,RELEASED,2024-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,2026-09-15,2026-09-15-CLR-03,"DEL ROSARIO, GABBY O.",BALLESTEROS DISTRICT HOSPITAL,"RESIGNATION EFFECTIVE FEBRUARY 26, 2026",RELEASED,2026-09-17,LEOVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,2026-09-15,2026-09-15-CLR-04,"DORANO, KRISHA S.",BALLESTEROS DISTRICT HOSPITAL,"MATERNITY LEAVE EFFECTIVE OCTOBER 30, 2026",RELEASED,2026-09-17,LEOVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,2026-09-15,2026-09-15-CLR-05,"LIONGSON, DEVON REY S.",NUESTRA SEÑORA DE PIAT DISTRICT HOSPITAL,TRAVEL ABROAD (VIETNAM) SEPTEMBER 30 TO OCTOBE...,RELEASED,2026-09-15,MA'AM NERISSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,2026-09-17,2026-09-17-CLR-01,"GILBUENA, PALOMA S.",GOVERNOR'S OFFICE,"TRAVEL ABROAD (THAILAND) OCTOBER 1-4, 2026",RELEASED,2026-09-17,SIR JAYSON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2026-09-18,2026-09-18-CLR-01,"VENTOLERO, ED ARMAND T.",SANGGUNIANG PANLALAWIGAN OFFICE,"TRAVEL ABROAD ( SINGAPORE) DECEMBER 20 - 29, 2026",RELEASED,2026-09-18,SIR RONNIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- [AOsMEMOs] ---

,2026-01-26 00:00:00,2026-01-23 00:00:00,EO-2026-01,EXECUTIVE ORDER NO. 01 - STREAMLINING AND RATIONALIZING BUREAUCRATIC PROCESSES THROUGH FUNCTIONAL GROUPING OF DEPT. AND OFFICES,GO,2026-01-26-COM-IN-04
0,2026-01-29,2026-01-28,AO-2026-02,ORDER ADOPTING THE GUIDELINES ON THE USE AND O...,GO,2026-01-29-COM-IN-01
1,2026-02-05,2026-01-21,AO-2026-1A,APPROVING AND ADOPTING THE JOINT RESOLUTION NO...,GO,2026-02-05-COM-IN-05
2,2026-02-05,2026-02-05,AO-2026-03,SUPPLEMENTAL ADMINISTRATIVE ORDER STRENGTHENIN...,GO,2026-02-05-COM-IN-10
3,2026-02-16,2026-02-13,EO-2026-06,RECONSTITUTING THE COMPREHENSIVE DEVELOPMENT P...,GO,2026-02-16-COM-IN-03
4,2026-03-13,2026-02-23,AO-2026-09,INSTITUTING THE STANDARD RATES FOR MEALS AND S...,PA,2026-03-13-COM-IN-01
5,2026-03-13,2026-03-13,EO-2026-11,AN EXECUTIVE ORDER ADOPTING ENERGY CONSERVATIO...,PA,2026-03-13-COM-IN-02
6,2026-03-17,2026-03-17,AO-2026-10,"AN ORDER PRESCRIBING COMPREHENSIVE POLICIES, G...",GO,2026-03-17-COM-IN-03
7,2026-03-30,2026-03-19,MEMO-2026-34A,MEMORANDUM 34A: REQUEST FOR PERMANENT ALTERNAT...,GO,NaN
8,2026-04-13,2026-04-13,MEMO-2026-04-13-01,DOCUMENTARY REQUIREMENTS FOR REIMBURSEMENT OF ...,ACCOUNTING,NaN
9,2026-04-14,2026-04-06,MEMO-2026-41C,DIRECTIVE ON MANDATORY COMPLIANCE WITH REPUBLI...,GO,NaN
10,2026-04-14,2026-04-06,MEMO-2026-41,REITERATE THE SUBMISSION OF THE PPA FOR POSSIB...,GO,NaN
11,2026-04-27,2026-04-22,MEMO-2026-28,MEMORANDUM ORDER NO. 28 S. 2026 ADOPTION OF LA...,PA,NaN
12,2026-05-11,2026-05-11,AO-2026-13,REORGANIZING THE ADMINISTRATIVE AND FINANCIAL ...,GO,NaN

--- [LEAVES] ---

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
0,2024-10-28,NaT,2024-10-28-LEAVE-IN-01,"GARMA,JEANNA C.",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-10-29,APPROVED
1,2024-11-01,NaT,2024-11-01-LEAVE-01,"URSULUM,MARELLA PEARL",VACATION LEAVE,TRAVEL ABROAD,NaN,2024-11-12,APPROVED
2,2024-11-01,NaT,2024-11-01-LEAVE-02,"URSULUM,MARELLA PEARL",MANDATORY,TRAVEL ABROAD,NaN,2024-11-12,APPROVED
3,2024-11-05,NaT,2024-11-05-LEAVE-IN-01,"DELA CRUZ, JOLIE M.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-05,APPROVED
4,2024-11-12,NaT,2024-11-12-LEAVE-IN-01,"GERVACIO, JENNIFER D.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-12,APPROVED
...,...,...,...,...,...,...,...,...,...
652,2026-09-21,2026-09-21,2026-09-21-LEAVE-02,"ABAD, ALYZA L.",WELLNESS LEAVE,NaN,"SEPTEMBER 25 & 28, 2026",NaT,NaN
653,2026-09-21,2026-09-21,2026-09-21-LEAVE-03,"URSULUM, MARELLA PEARL JOIE",SICK LEAVE,NaN,"SEPTEMBER 18,2026",NaT,NaN
654,2026-09-22,2026-09-22,2026-09-22-LEAVE-01,"PEREZ, BENEDICT S.",SICK LEAVE,NaN,"SEPTEMBER 21, 2026",NaT,NaN
655,2026-09-22,2026-09-22,2026-09-22-LEAVE-02,"GARMA, JEANNA C.",WELLNESS LEAVE,NaN,"SEPTEMBER 6 & 7, 2026",NaT,NaN
656,2026-09-23,2026-09-23,2026-09-23-LEAVE-01,"CORPUZ, CRISEL S.",SICK LEAVE,NaN,"SEPTEMBER 22, 2026",NaT,NaN

In [41]:
print(df.shape) #dimensionality: (rows, columns)
print(df.columns.tolist()) #schema / feature names
print(df.dtypes) #data types inferred by pandas
print(df.isna().sum()) #missing-value detection
print(df.duplicated().sum()) #check duplicate records

(657, 9)
['DATE FILED', 'TRANSMITAL DATE', 'CONTROL#', 'NAME', 'TYPE OF LEAVE', 'REMARKS', 'DAY/S APPLIED', 'DATE RECEIVED', 'STATUS']
DATE FILED         datetime64[us]
TRANSMITAL DATE    datetime64[us]
CONTROL#                      str
NAME                          str
TYPE OF LEAVE                 str
REMARKS                       str
DAY/S APPLIED                 str
DATE RECEIVED      datetime64[us]
STATUS                        str
dtype: object
DATE FILED           6
TRANSMITAL DATE     44
CONTROL#             4
NAME                 4
TYPE OF LEAVE        5
REMARKS            616
DAY/S APPLIED       45
DATE RECEIVED       45
STATUS              38
dtype: int64
3

In [46]:
print(f"\n---{sheets}---")
print("Shape", df.shape)
print("Duplicates:", df.duplicated().sum())
print("\nMissing values:")
print(df.isna().sum())

---LEAVES---
Shape (657, 9)
Duplicates: 3

Missing values:
DATE FILED           6
TRANSMITAL DATE     44
CONTROL#             4
NAME                 4
TYPE OF LEAVE        5
REMARKS            616
DAY/S APPLIED       45
DATE RECEIVED       45
STATUS              38
dtype: int64

In [48]:
#investigate the 3 duplicates 
duplicates = df[df.duplicated(keep=False)]
display(duplicates)

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
209,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
234,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
393,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
429,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [50]:
#detect empty rows
empty_rows  = df[df.isna().all(axis=1)]
display(empty_rows)

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
209,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
234,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
393,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
429,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [58]:
#how="all" means : drop a row only when every column is Null
df = df.dropna(how="all")

In [59]:
#inspect categorical columns
print(df["TYPE OF LEAVE"].value_counts(dropna=False))
print(df["STATUS"].value_counts(dropna=False))

TYPE OF LEAVE
SICK LEAVE                204
COMPENSATORY              132
SPL                       109
MANDATORY                  86
WELLNESS LEAVE             49
MONETIZATION               27
VACATION LEAVE             19
SPECIAL PRIVILEGE           5
MANDATORY LEAVE             4
COC                         4
SPECIAL EMERGENCY           2
MANDATORY/FORCED LEAVE      2
LEAVE WITHOUT PAY           2
STUDY LEAVE                 1
NaN                         1
TERMINAL                    1
SICK LEAVE\nPATERNITY       1
MATERNITY                   1
MANDATORY & SPL             1
PATERNITY LEAVE             1
FORCED LEAVE                1
Name: count, dtype: int64
STATUS
APPROVED       614
NaN             34
CANCELLED        4
DISAPPROVED      1
Name: count, dtype: int64

In [61]:
df["TYPE OF LEAVE"] = (
    df["TYPE OF LEAVE"]
    .str.strip()
    .str.upper()
)

#You should see some categories merge.
df["TYPE OF LEAVE"].value_counts(dropna=False)

TYPE OF LEAVE
SICK LEAVE                204
COMPENSATORY              132
SPL                       109
MANDATORY                  86
WELLNESS LEAVE             49
MONETIZATION               27
VACATION LEAVE             19
SPECIAL PRIVILEGE           5
MANDATORY LEAVE             4
COC                         4
SPECIAL EMERGENCY           2
MANDATORY/FORCED LEAVE      2
LEAVE WITHOUT PAY           2
STUDY LEAVE                 1
NaN                         1
TERMINAL                    1
SICK LEAVE\nPATERNITY       1
MATERNITY                   1
MANDATORY & SPL             1
PATERNITY LEAVE             1
FORCED LEAVE                1
Name: count, dtype: int64